### ISSUE TITLE
Singleplayer for linux is super out of date

### ISSUE THREAD

**Issue by ryannathans** [2009scape/2009scape.github.io#213]
https://2009scape.org/site/game_guide/singleplayer.html

![image](https://user-images.githubusercontent.com/1307375/233875190-d823e055-cd4a-4f5c-a329-557912d136f6.png)

this URL is unmaintained

https://gitlab.com/2009scape/singleplayer/windows now points to the crossplatform release

**Comment by dginovker** [comment]
Fixed
