### ISSUE TITLE
Black dragon doesn't appear in drop table search

### ISSUE THREAD

**Issue by zsrv** [2009scape/2009scape.github.io#218]
The Black Dragon is not returned as a result in the "Drop Tables" search on the [drop tables page](https://2009scape.org/services/m=data/drop-table/). The King Black Dragon, however, is returned.

The Black Dragon does appear if I use the "Item Sources" search to search for an item that the Black Dragon drops (e.g. Draconic visage).

**Comment by downthecrop** [comment]
There are a couple of entries like this. Probably something GPT-4 can see in a millisecond.

I'll do this later today 👍
